name: kipoi-veff2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=0.2
  - bcolz=1.2.1
  - bedtools=2.29.2
  - blas=1.0
  - blosc=1.20.1
  - bokeh=2.3.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - click=7.1.2
  - cloudpickle=1.6.0
  - coloredlogs=15.0
  - contextvars=2.4
  - cudatoolkit=10.0.130
  - cudnn=7.6.5.32
  - cytoolz=0.11.0
  - cyvcf2=0.30.6
  - dask=2021.3.0
  - dask-core=2021.3.0
  - distributed=2021.3.0
  - freetype=2.10.4
  - fsspec=0.9.0
  - genomelake=0.1.4
  - hdf5=1.10.4
  - heapdict=1.0.1
  - htslib=1.10.2
  - humanfriendly=9.1
  - immutables=0.14
  - intel-openmp=2020.2
  - jinja2=2.11.3
  - jpeg=9d
  - krb5=1.17.2
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.76.0
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libwebp-base=1.2.0
  - llvm-openmp=11.1.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - lzo=2.10
  - markupsafe=1.1.1
  - maxentpy=0.0.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.2.0
  - mock=4.0.3
  - msgpack-python=1.0.0
  - ncurses=6.2
  - ninja=1.10.1
  - numexpr=2.7.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.1.4
  - partd=1.1.0
  - pillow=8.0.1
  - pip=20.2.4
  - psutil=5.7.3
  - pybedtools=0.8.1
  - pybigwig=0.3.17
  - pycparser=2.20
  - pyparsing=2.4.7
  - pysam=0.16.0.1
  - pytables=3.5.2
  - python=3.6.13
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.3.1
  - pytz=2021.1
  - pyyaml=5.3.1
  - readline=8.1
  - scipy=1.5.3
  - setuptools=52.0.0
  - six=1.15.0
  - sortedcontainers=2.3.0
  - sqlite=3.35.4
  - tblib=1.7.0
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - appdirs==1.4.4
    - argcomplete==1.12.2
    - argh==0.26.2
    - arrow==1.0.3
    - attrs==20.3.0
    - binaryornot==0.4.4
    - bleach==1.5.0
    - cfgv==3.2.0
    - chardet==4.0.0
    - colorlog==4.8.0
    - cookiecutter==1.7.2
    - dataclasses==0.8
    - deprecation==2.1.0
    - distlib==0.3.1
    - docker==5.0.0
    - enum34==1.1.10
    - filelock==3.0.12
    - future==0.18.2
    - gffutils==0.10.1
    - h5py==2.10.0
    - html5lib==0.9999999
    - identify==2.2.2
    - idna==2.10
    - importlib-metadata==3.10.0
    - importlib-resources==5.1.2
    - iniconfig==1.1.1
    - jinja2-time==0.2.0
    - keras==2.1.6
    - kipoi==0.6.31
    - kipoi-conda==0.2.2
    - kipoi-utils==0.3.8
    - kipoiseq==0.5.2
    - markdown==3.3.4
    - nodeenv==1.5.0
    - pluggy==0.13.1
    - poyo==0.5.0
    - pre-commit==2.12.0
    - protobuf==3.15.7
    - py==1.10.0
    - pyfaidx==0.5.9.5
    - pytest==6.2.3
    - python-slugify==4.0.1
    - related==0.7.2
    - requests==2.25.1
    - scikit-learn==0.19.0
    - simplejson==3.17.2
    - tensorflow==1.4.1
    - tensorflow-tensorboard==0.4.0
    - text-unidecode==1.3
    - tinydb==4.4.0
    - toml==0.10.2
    - tqdm==4.60.0
    - urllib3==1.26.4
    - virtualenv==20.4.3
    - websocket-client==0.58.0
    - werkzeug==1.0.1
    - zipp==3.4.1  
prefix: /usr/local/envs/kipoi-veff2
